import { createHash } from "crypto";
import { mkdir, readFile, rm, writeFile } from "fs/promises";
import path from "path";

/**
 * Local filesystem blob store for Milestone 12 file_objects.
 * Provider name stored in DB: `local_fs`. Bytes live under `.file-store/`
 * (gitignored, server-only — never served as static assets).
 * storage_key format: inst/{institutionId}/{fileId}/{filename}
 */

const ROOT = path.join(process.cwd(), ".file-store");

export class FileStoreError extends Error {
  constructor(message: string) {
    super(message);
    this.name = "FileStoreError";
  }
}

function keyToPath(storageKey: string): string {
  // storage_key is always generated by createFileObject — reject traversal.
  if (
    !storageKey ||
    storageKey.includes("..") ||
    storageKey.includes("\0") ||
    !storageKey.startsWith("inst/")
  ) {
    throw new FileStoreError("Invalid storage key");
  }
  const resolved = path.resolve(ROOT, storageKey);
  const rootResolved = path.resolve(ROOT);
  if (resolved !== rootResolved && !resolved.startsWith(rootResolved + path.sep)) {
    throw new FileStoreError("Invalid storage key path");
  }
  return resolved;
}

export function sha256Hex(bytes: Buffer): string {
  return createHash("sha256").update(bytes).digest("hex");
}

export async function putFileBytes(
  storageKey: string,
  bytes: Buffer
): Promise<{ checksum: string }> {
  const abs = keyToPath(storageKey);
  await mkdir(path.dirname(abs), { recursive: true });
  await writeFile(abs, bytes, { flag: "wx" });
  return { checksum: sha256Hex(bytes) };
}

export async function getFileBytes(storageKey: string): Promise<Buffer> {
  const abs = keyToPath(storageKey);
  try {
    return await readFile(abs);
  } catch {
    throw new FileStoreError("File content not available");
  }
}

export async function deleteFileBytes(storageKey: string): Promise<void> {
  const abs = keyToPath(storageKey);
  try {
    await rm(abs, { force: true });
  } catch {
    /* best-effort — metadata soft-delete is authoritative */
  }
}
