-- Better Auth Schema Migration
-- Generated from Better Auth 1.7.5 documented PostgreSQL schema
-- Configuration: schemaName="auth", generateId="uuid", emailAndPassword enabled
--
-- IMPORTANT: This file is for REVIEW ONLY. Do NOT execute against Neon.
-- Generated by: manual construction based on Better Auth docs
-- Better Auth CLI (npx auth generate) requires a live database connection.

-- Create the auth schema
CREATE SCHEMA IF NOT EXISTS "auth";

-- ============================================================
-- user table
-- ============================================================
CREATE TABLE "auth"."user" (
    "id" uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    "name" text NOT NULL DEFAULT '',
    "email" text NOT NULL,
    "emailVerified" boolean NOT NULL DEFAULT false,
    "image" text,
    "createdAt" timestamptz NOT NULL DEFAULT now(),
    "updatedAt" timestamptz NOT NULL DEFAULT now()
);

CREATE UNIQUE INDEX "auth"."user_email_idx" ON "auth"."user" ("email");

-- ============================================================
-- session table
-- ============================================================
CREATE TABLE "auth"."session" (
    "id" uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    "token" text NOT NULL,
    "userId" uuid NOT NULL REFERENCES "auth"."user"("id") ON DELETE CASCADE,
    "expiresAt" timestamptz NOT NULL,
    "ipAddress" text,
    "userAgent" text,
    "createdAt" timestamptz NOT NULL DEFAULT now(),
    "updatedAt" timestamptz NOT NULL DEFAULT now()
);

CREATE UNIQUE INDEX "auth"."session_token_idx" ON "auth"."session" ("token");
CREATE INDEX "auth"."session_userId_idx" ON "auth"."session" ("userId");

-- ============================================================
-- account table
-- ============================================================
CREATE TABLE "auth"."account" (
    "id" uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    "userId" uuid NOT NULL REFERENCES "auth"."user"("id") ON DELETE CASCADE,
    "providerId" text NOT NULL,
    "accountId" text NOT NULL,
    "refreshToken" text,
    "accessToken" text,
    "accessTokenExpiresAt" timestamptz,
    "idToken" text,
    "scope" text,
    "password" text,
    "createdAt" timestamptz NOT NULL DEFAULT now(),
    "updatedAt" timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX "auth"."account_userId_idx" ON "auth"."account" ("userId");
CREATE UNIQUE INDEX "auth"."account_provider_account_idx" ON "auth"."account" ("providerId", "accountId");

-- ============================================================
-- verification table
-- ============================================================
CREATE TABLE "auth"."verification" (
    "id" uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    "identifier" text NOT NULL,
    "token" text NOT NULL,
    "expiresAt" timestamptz NOT NULL,
    "createdAt" timestamptz NOT NULL DEFAULT now(),
    "updatedAt" timestamptz NOT NULL DEFAULT now()
);

CREATE UNIQUE INDEX "auth"."verification_identifier_token_idx" ON "auth"."verification" ("identifier", "token");
